apiVersion: v1
kind: Service
metadata:
  name: llm-gateway-service
  namespace: edge-apps
  labels:
    app: llm
spec:
  selector:
    app: llm
  ports:
  - name: proxy-http
    protocol: TCP
    port: 80
    targetPort: 8001
  type: ClusterIP